sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: SmallRedBird
    username: root
    password: 123321wwww
  alioss:
    endpoint: abc
    access-key-id: abc
    access-key-secret: abc
    bucket-name: abc
  redis:
    host: localhost
    port: 6379